spring.application.name=loja_virtual_BackEnd

spring.datasource.url=jdbc:postgresql://localhost:5432/loja_virtual_mentoria
spring.datasource.username=postgres
spring.datasource.password=was

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.devtools.restart.enabled=true
server.port=8080
